context.modules = [
{   name = libpipewire-module-loopback
    args = {
        node.description = "Yamaha AG08 5/6"
        capture.props = {
            node.name = "AG08_56"
            media.class = "Audio/Sink"
            audio.channels = 2  # OBS Pipewire plugin won't work without
            audio.position = [ FL FR ]
        }
        playback.props = {
            node.name = "playback.AG08_56"
            audio.position = [ AUX2 AUX3 ]
            target.object = "alsa_output.usb-Yamaha_Corporation_Yamaha_AG08-00.pro-output-0"
        }
    }
}
]
