context.modules = [
{   name = libpipewire-module-loopback
    args = {
        node.description = "Yamaha AG08 Streaming"
        capture.props = {
            audio.position = [ AUX0 AUX1 ]
            node.target = "alsa_input.usb-Yamaha_Corporation_Yamaha_AG08-00.pro-input-0"
        }
        playback.props = {
            node.name = "AG08_streaming"
            media.class = "Audio/Source"
            audio.channels = 2  # OBS Pipewire plugin won't work without
            audio.position = [ FL FR ]
        }
    }
}
]
